# Generated by Django 4.0.3 on 2022-03-28 21:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_mygallery_alter_photo_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mygallery',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
